[versions]
agp = "8.7.3"
converterGson = "2.9.0"
converterMoshi = "2.9.0"
countryPickerAndroid = "2.0"
databindingRuntime = "8.8.0"
fragmentKtx = "1.8.5"
glide = "4.15.1"
gson = "2.10.1"
hiltAndroid = "2.57"
kotlin = "2.1.0"
coreKtx = "1.15.0"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
appcompat = "1.7.0"
lottie = "4.2.0"
lottieswiperefreshlayout = "1.0.0"
lottieVersion = "5.2.0"
material = "1.12.0"
activity = "1.10.0"
constraintlayout = "2.2.0"
media3Exoplayer = "1.8.0"
viewpagerindicator = "1.2.3"
dagger = "2.57"
okhttp = "5.0.0-alpha.3"
playServicesLocation = "21.3.0"
sdpAndroid = "1.1.0"
navigationFragmentKtx = "2.7.7"
imagepicker = "2.1"
navigationUiKtx = "2.7.7"
sspAndroid = "1.1.0"
google-services = "4.4.3"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-databinding-runtime = { module = "androidx.databinding:databinding-runtime", version.ref = "databindingRuntime" }
androidx-fragment-ktx = { module = "androidx.fragment:fragment-ktx", version.ref = "fragmentKtx" }
androidx-media3-exoplayer = { module = "androidx.media3:media3-exoplayer", version.ref = "media3Exoplayer" }
androidx-media3-ui = { module = "androidx.media3:media3-ui", version.ref = "media3Exoplayer" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "converterGson" }
country-picker-android = { module = "com.github.yesterselga:country-picker-android", version.ref = "countryPickerAndroid" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hiltAndroid" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hiltAndroid" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-navigation-fragment-ktx-v277 = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigationFragmentKtx" }
androidx-navigation-ui-ktx-v277 = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigationUiKtx" }
logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }
lottie = { module = "com.airbnb.android:lottie", version.ref = "lottie" }
lottie-v520 = { module = "com.airbnb.android:lottie", version.ref = "lottieVersion" }
lottieswiperefreshlayout = { module = "com.github.nabil6391:LottieSwipeRefreshLayout", version.ref = "lottieswiperefreshlayout" }
viewpagerindicator = { module = "com.github.zhpanvip:viewpagerindicator", version.ref = "viewpagerindicator" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
dagger = { group = "com.google.dagger", name = "dagger", version.ref = "dagger" }
dagger_compiler = { group = "com.google.dagger", name = "dagger-compiler", version.ref = "dagger" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
play-services-location = { module = "com.google.android.gms:play-services-location", version.ref = "playServicesLocation" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "converterMoshi" }
imagepicker = { module = "com.github.dhaval2404:imagepicker", version.ref = "imagepicker" }
sdp-android = { module = "com.intuit.sdp:sdp-android", version.ref = "sdpAndroid" }
ssp-android = { module = "com.intuit.ssp:ssp-android", version.ref = "sspAndroid" }




[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
google-services = {id = "com.google.gms.google-services", version.ref = "google-services"}
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hiltAndroid" }
kotlin1kept = { id = "kotlin-kapt" }
